apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  #Los valores debe estar en base64 no en texto plano
  #Base64 String:  postgres :: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM= 
  #root :: cm9vdA==
  DB_PASSWORD: cm9vdA==